let myScreenCaptureSprite2: Sprite = null
let mySprite2: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
let mySprite = sprites.create(img`
    ........................
    ....ffffff..............
    ..ffeeeef2f.............
    .ffeeeef222f............
    .feeeffeeeef...cc.......
    .ffffee2222ef.cdc.......
    .fe222ffffe2fcddc.......
    fffffffeeeffcddc........
    ffe44ebf44ecddc.........
    fee4d41fddecdc..........
    .feee4dddedccc..........
    ..ffee44e4dde...........
    ...f222244ee............
    ...f2222e2f.............
    ...f444455f.............
    ....ffffff..............
    .....fff................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
let s = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . b 5 5 b . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . b b b b b 5 5 5 5 5 5 5 b . . 
    . b d 5 b 5 5 5 5 5 5 5 5 b . . 
    . . b 5 5 b 5 d 1 f 5 d 4 f . . 
    . . b d 5 5 b 1 f f 5 4 4 c . . 
    b b d b 5 5 5 d f b 4 4 4 4 b . 
    b d d c d 5 5 b 5 4 4 4 4 4 4 b 
    c d d d c c b 5 5 5 5 5 5 5 b . 
    c b d d d d d 5 5 5 5 5 5 5 b . 
    . c d d d d d d 5 5 5 5 5 d b . 
    . . c b d d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `, SpriteKind.Player)
screenCapture.pause(1)
let myScreenCaptureSprite = screenCapture.createCaptureScreenImageSprite()
sprites.destroy(mySprite)
sprites.destroy(s)
controller.moveSprite(myScreenCaptureSprite)
scene.cameraFollowSprite(myScreenCaptureSprite)
timer.after(500, function () {
    screenRotator.rotateScreenEnabled(true)
    timer.after(1999, function () {
        screenRotator.rotateScreenEnabled(false)
        mySprite2 = sprites.create(img`
            ........................
            ....ffffff..............
            ..ffeeeef2f.............
            .ffeeeef222f............
            .feeeffeeeef...cc.......
            .ffffee2222ef.cdc.......
            .fe222ffffe2fcddc.......
            fffffffeeeffcddc........
            ffe44ebf44ecddc.........
            fee4d41fddecdc..........
            .feee4dddedccc..........
            ..ffee44e4dde...........
            ...f222244ee............
            ...f2222e2f.............
            ...f444455f.............
            ....ffffff..............
            .....fff................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Player)
        mySprite2.z += 44
        controller.moveSprite(mySprite2)
        controller.moveSprite(myScreenCaptureSprite, 0, 0)
        scene.cameraFollowSprite(mySprite2)
        screenCapture.pause(2222)
        myScreenCaptureSprite2 = screenCapture.createCaptureScreenImageSprite()
    })
})
game.onUpdate(function () {
    myScreenCaptureSprite.sayText("" + mySprite.x + "," + mySprite.y)
})
game.onUpdate(function () {
    screenRotator.changeRotation(myScreenCaptureSprite, 100)
})
